### ISSUE TITLE
autoconf failures on mingw

### ISSUE THREAD

**Issue by trippleflux** [bdwgc/bdwgc#16]
I am trying to compile bdwgc 7.2 release on mysys/mingw, while libatomic_ops compile without any problems, it seems that there is some problems on bdwgc autoconf script (configure.ac), it throws this error while issuing autoconf command from the autogen.sh

configure.ac:70: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:358: error: possibly undefined macro: AS_IF

if i added this exception lines into configure.ac
m4_pattern_allow([^dnl]) 
m4_pattern_allow([^AC_])
m4_pattern_allow([^AS_])
m4_pattern_allow([^m4])

it will succeed to generate the configure scripts but failed when configure process.

aclocal v 1.10
autoconf v 2.68

**Comment by rdp** [comment]
See also https://github.com/ivmai/bdwgc/issues/69
