### ISSUE TITLE
Prematurely Reclaimed Objects on Windows 10 after upgrade 1803 (April 2018)

### ISSUE THREAD

**Issue by ldeniau** [bdwgc/bdwgc#227]
We have a large application mixing C, C++, F77 and F90 and libraries with many global variables that suddenly crashed during its initialisation once we upgraded Windows 10 with 1803. This was true for recent versions as well as for old versions compiled years ago (i.e. taking the binary as is). All versions are running well on older Windows, or all Linux and MacOSX.

I succeeded to reduce the code run between the main() and the point where the GC reclaimed prematurely the memory allocated (still referenced by a global variable), to [1 GC_malloc+1 GC_malloc_atomic] x2 and _nothing else_ (second GC_malloc_atomic can be replaced by GC_malloc without success). The second GC_malloc is reusing the memory allocated by the first GC_malloc, still referenced by the global variable, _if I put_ a GC_gcollect() in between to trigger the problem earlier. I tried with gc 7.2f and 7.6.4, and followed all recommendations on the website in section Prematurely Reclaimed Objects (e.g. compiling the GC with all kind of defines and flags).

If I reference the memory allocated and prematurely reclaimed by another global variable before the GC_gcollect() in the same translation unit (object file), then the GC sees the reference and does not reclaim the memory. A debugger backtrace suggests a problem with the library ntdll.dll, see the dependencies at the end.

So I suspect that the GC does not see anymore one of the Text/Data segment of the application where the global variables are stored, for whatever reason. And this occurred independently of the code, as versions compiled years ago were working before and crashing after the W10 upgrade 1803 (and still work on all other platforms/architectures). So the W10 upgrade 1803 changed something in the system API/ABI of some DLL, leading to this strange result (threads local storage, eager memory (un)mapping, location of pages). I tried to make a simple example showing the problem, but it fails to reproduce it, not surprising since all the GC tests passed. So it is possible that gfortran or g++ pre-initialisations (before main()) or the size of the binairy (23MB) are relevant to trig the problem.

Any idea how I could provide/get more useful information and find a solution?

Best,
Laurent.

```
make infobindep
** Computing binaries dependencies in build/
build/madx-win64-gnu.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff84f830000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff84d1c0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff84c9a0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff84eef0000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ff84d3a0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ff84bc00000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ff84eff0000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ff84c620000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ff84cc20000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff84c8a0000)
```

**Comment by ivmai** [comment]
I think this issue duplicates #219, please check commit 19bf43c
