### ISSUE TITLE
Is 8.2.0 a stable release?

### ISSUE THREAD

**Issue by carlocab** [bdwgc/bdwgc#455]
I noticed that `8.2.0` is currently marked as a pre-release here on GitHub (see https://github.com/ivmai/bdwgc/releases/tag/v8.2.0).

However, some downstream packagers appear to have picked it up: https://repology.org/project/boehm-gc/versions

#368 also suggests that `8.2.x` was expected some time last year.

Could you clarify the status of the 8.2.0 release, please? Thanks.

**Comment by ivmai** [comment]
Hi Carlo.

v8.2.0 is experimental. The stabilization turned out to much more than planned initially, sorry about this. My focus is on releasing v8.2.2 as soon as possible. The current estimation the release will be made within July.

**Comment by carlocab** [comment]
Hi Ivan, thanks for the clarification. No worries on the delay.

In case it's helpful for your testing, we ran a build of 8.2.0 briefly in Homebrew CI (which includes some rudimentary dependent package tests, but we do run `make check` for `bdwgc`). This revealed no problems.

Our CI runs on macOS (10.15, 11, and 12, both x86-64 and arm64) and Linux (Ubuntu 16.04, x86-64).

**Comment by ivmai** [comment]
The stable one is now released - https://github.com/ivmai/bdwgc/releases/tag/v8.2.2

**Comment by carlocab** [comment]
Thank you for the update.
